### PR TITLE
develop/prepare-39

### PR DESCRIPTION
**Pull request by Segelzwerg**
Some mocking behavior is not working with <3.8

### CODE REVIEW

**Comment by hugovk** [comment]
Pillow 8.0.0 supporting Python 3.9 is now out!

* https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html
* https://pypi.org/project/Pillow/8.0.0/
* https://twitter.com/PythonPillow/status/1316452445824921602

**Comment by Segelzwerg** [comment]
> Pillow 8.0.0 supporting Python 3.9 is now out!
> 
> * https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html
> * https://pypi.org/project/Pillow/8.0.0/
> * https://twitter.com/PythonPillow/status/1316452445824921602

yes, @hugovk thx for the info. We're still waiting for opencv-python who are waiting for numpy.

**Comment by hugovk** [comment]
NumPy is waiting on 3.9 for Windows on Azure Pipelines, due out early next week:

https://github.com/actions/virtual-environments/issues/1740#issuecomment-709382218

**Comment by Segelzwerg** [comment]
> NumPy is waiting on 3.9 for Windows on Azure Pipelines, due out early next week:
> 
> [actions/virtual-environments#1740 (comment)](https://github.com/actions/virtual-environments/issues/1740#issuecomment-709382218)

Thx for the update. We currently in no need to rush it, although @iTitus did a lot of restructuring which we will release simultaneously.

**Pull request merged**
